### ISSUE TITLE
Datasets.zip appears to be corrupted

### ISSUE THREAD

**Issue by PatWalters** [dahvida/GBM_Benchmarking#3]
```
unzip Datasets.zip
Archive:  Datasets.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Datasets.zip or
        Datasets.zip.zip, and cannot find Datasets.zip.ZIP, period.
```

**Comment by dahvida** [comment]
Unfortunately I wasn't able to reproduce this error. I tried cloning and unzipping this repo on two different machines, both with Windows 11 and Ubuntu 20.04, but I haven't encountered any issues. Uploading the datasets without compression is not an option at the moment, so I'm unsure how to proceed. 

However, you can find the same versions of the datasets we used here:
- Moleculenet: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00479-8
- Moldata: https://github.com/LumosBio/MolData
- Regression: https://pubs.acs.org/doi/10.1021/acs.jcim.8b00542

Alternatively, just send me an email and I'll be happy to send you the data directly.

**Comment by PatWalters** [comment]
Thanks for your response.  I figured it out.  Datasets.zip is 55MB which is larger than the 50MB limit imposed by GitHub.  In order to download the file one needs to have git-lfs (large file storage) installed. 
https://git-lfs.com/
Once I installed git-lfs, everything worked. 

Btw, in the future, it would be a good idea to avoid MoleculeNet as a benchmark. 
https://practicalcheminformatics.blogspot.com/

**Comment by dahvida** [comment]
Ah I see, I'm happy to hear that. I'll add to the README that git-lfs needs to be installed to download the data then, thanks for letting me know. 

Regarding MoleculeNet, I absolutely agree, in hindsight it wasn't necessarily the best pick for this type of study, despite its popularity. MoleculeACE would've been a good pick, but when we started working on this project it wasn't public yet and we were focusing more on classification. Hopefully in the future there will be more pertinent benchmarks for these types of studies.
